import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from "./providers";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Header from "./components/Header";
import Footer from "./components/Footer";
import BackgroundBlur from "./components/BackgroundBlur";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Sam Morgan | Web Developer",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full" suppressHydrationWarning>
			<body className={`${inter.className} bg-white dark:bg-black`}>
				<Providers>
					<UserProvider>
						<div className="h-screen flex flex-col">
							<div className="flex-shrink flex-grow-0 z-0">
								<BackgroundBlur />
							</div>
							<Header />
							{children}
							<Footer />
						</div>
					</UserProvider>
				</Providers>
			</body>
		</html>
	);
}
